export const NAVBAR_PAGES = [
  // {
  //   label: 'navbar.color_picker',
  //   link: 'color-picker',
  //   icon: 'color_picker',
  //   count: 1,
  //   order: 0,
  //   roles: ['mode_dev', 'trainee'],
  // },
  {
    label: 'navbar.json_to_typescript',
    link: 'json-format-validate',
    icon: 'brackets_curly',
    count: 1,
    order: 1,
    roles: ['mode_dev', 'trainee'],
  },
  // {
  //   label: 'navbar.hash_generator',
  //   link: 'hash-generator',
  //   icon: 'binary_lock',
  //   count: 1,
  //   order: 2,
  //   roles: ['mode_dev', 'trainee'],
  // },
  {
    label: 'navbar.text_convert',
    link: 'text-convert',
    icon: 'text_size',
    count: 1,
    order: 3,
    roles: ['mode_dev', 'trainee'],
  },
  // {
  //   label: 'navbar.qrcode_generator',
  //   link: 'qrcode-generator',
  //   icon: 'qrcode',
  //   count: 1,
  //   order: 4,
  //   roles: ['mode_dev', 'trainee'],
  // },
  // {
  //   label: 'navbar.base_to_image',
  //   link: 'base-to-image',
  //   icon: 'message_code',
  //   count: 1,
  //   order: 5,
  //   roles: ['mode_dev', 'trainee'],
  // },
  // {
  //   label: 'navbar.image_converter',
  //   link: 'image-converter',
  //   icon: 'image',
  //   count: 1,
  //   order: 6,
  //   roles: ['mode_dev', 'trainee'],
  // },
  // {
  //   label: 'navbar.diff_checker',
  //   link: 'diff-checker',
  //   icon: 'diff_checker',
  //   count: 1,
  //   order: 7,
  //   roles: ['mode_dev', 'trainee'],
  // },
  // {
  //   label: 'Markdown Preview',
  //   link: 'markdown-preview',
  //   icon: 'markdown',
  //   count: 1,
  //   order: 101,
  //   roles: ['mode_dev'],
  // },
  // {
  //   label: 'Random Password',
  //   link: 'random-password',
  //   icon: 'key',
  //   count: 1,
  //   order: 102,
  //   roles: ['mode_dev'],
  // },
  // {
  //   label: 'Lorem Ipsum Generator',
  //   link: 'lorem-ipsum-generator',
  //   icon: 'square_l',
  //   count: 1,
  //   order: 103,
  //   roles: ['mode_dev'],
  // }
]
